### ISSUE TITLE
scales 1.0.0 change to hue_pal() breaks fbplot

### ISSUE THREAD

**Issue by dpseidel** [ntarabelloni/roahd#1]
The upcoming scales 1.0.0 release includes some minor changes to `hue_pal()` that according to my revdep checks will break the multivariate boxplot example used in the documentation of `fbplot()` and your vignette. The error seems to be cause at [L572](https://github.com/ntarabelloni/roahd/blob/400866fabc64a2933b2fe0e1cb10552457fbafb3/R/fbplot.R#L572) where you call `hue_pal()(length(ID_out))`. With scales 0.5.0 this returned an empty string where as in the newest version it fails, returning the error `Error: Must request at least one colour from a hue palette.` because `length(ID_out) == 0`.

The release is expected out by next week, and I wanted to give you a heads up about this minor breaking change.

**Comment by dpseidel** [comment]
Some more information: the change was made in r-lib/scales#81 so that arguments hue_pal arguments are forcibly evaluated on each call. This is the appropriate behavior but before the change, arguments to hue_pal() inside a for loop (as is your case at L572) wouldn't be evaluated until the end of the loop -- preventing the error associated with `hue_pal()(0)` and outputting an empty character vector rather than an error.  The fix will simply need to involve proper handling of 0 lengths at L572.

**Comment by astamm** [comment]
Thanks @dpseidel. I have taken over the maintenance of the package. I will provide a fix soon.
