### ISSUE TITLE
Warning message in multivariate_outliegram when shift = TRUE

### ISSUE THREAD

**Issue by lorebon** [ntarabelloni/roahd#4]
Dear Astamm,

I kindly ask for your assistance: when I run the ‘multivariate_outliergram’ with ‘shift = TRUE’, I incur in the following warning: ‘In max(max_diffs) : no non-missing arguments to max; returning -Inf’.

While debugging, I found out that the following lines of code give the warning/error:

max_diff_max = maxs %>%
  dplyr::filter(obs %in% ID_non_outlying_Low_MEI ) %>%
  dplyr::group_by(obs) %>%
  dplyr::summarize(max_diff_max = max(max_diffs))

when handling points with low MEI.
 
When I run the command with ‘shift = FALSE’ I do not get any warning.
 
Thanks in advance.

**Comment by astamm** [comment]
Thanks @LorenzoBonasera for reporting that. It would be helpful that you define the `maxs` object so we can reproduce the issue. I know you sent it to me via email but it would be nice to have here a small minimal reproducible example.

**Comment by astamm** [comment]
Well since you seem not inclined to provide a reproducible example, I attempted a fix in the `multivariate-outliergram-bug` branch. Can you test it please and tell me if it solves your issue?

**Comment by lorebon** [comment]
Sorry for my late answer. 
It's hard for me to provide a small minimal reproducible example, since I work with huge amount of data and it's very difficult to "isolate" the problem in this setting.
I will test your fix, thank you!

**Comment by astamm** [comment]
Let me know if that does the trick, in which case I will make a PR and merge it to the master branch for next release.

**Comment by lorebon** [comment]
The fix does not work: I keep getting the same error.
Here is my reproducible example. It was taken inside the function 'manage_low_MEI_data', so it is easier to test it:

[mylocals.zip](https://github.com/astamm/roahd/files/8022052/mylocals.zip)

Let me know if this example can help you!

**Comment by astamm** [comment]
How did you install `roahd` from my branch?
The correct way is `devtools::install_github("astamm/roahd@multivariate-outliergram-bug")`.

**Comment by lorebon** [comment]
> How did you install `roahd` from my branch?

I directly added new lines of code to my own source file

**Comment by astamm** [comment]
If you install it the correct way do you still confirm it does not fix the issue?

**Comment by lorebon** [comment]
> If you install it the correct way do you still confirm it does not fix the issue?

Yes, I confirm. The condition `length(ID_non_outlying_Low_MEI) == 0` is not met by my example.

**Comment by astamm** [comment]
How do I load your data? There is no file extension.

**Comment by lorebon** [comment]
> How do I load your data? There is no file extension.

File is a .zip that contains a .rda file. You can load into RStudio through the command `example = load(file = 'mylocals.Rda')`

**Comment by astamm** [comment]
You should be good now.

**Comment by lorebon** [comment]
> You should be good now.

Yes, now it works properly. Thank you very much!
